### ISSUE TITLE
External Calendar - Module - problems after update to 1.40

### ISSUE THREAD

**Issue by kiwiradler** [humhub-contrib/external_calendar#51] opened 2023-07-18 08:50 UTC
After updating from 1.3.3 to 1.4 all my dates are displayed multiple times in the calendar. And it is not possible anymore to get to the point where I can edit, delete or renew the URL from the external calendar. What can I do?
<img width="295" alt="Bildschirmfoto 2023-07-17 um 16 32 31" src="https://github.com/humhub-contrib/external_calendar/assets/45717431/7da90f2f-fc16-4bc4-8da1-998771726196">
<img width="1149" alt="Bildschirmfoto 2023-07-17 um 16 33 02" src="https://github.com/humhub-contrib/external_calendar/assets/45717431/caa9b4d0-3e60-47d2-92b5-ee350b506dc4">

**Comment by right-berlin** [comment] 2023-08-30 08:42
Hello to all, i I have the same problem with multiple calendar entries.

**Comment by marc-farre** [comment] 2023-09-20 14:36
Duplicate of https://github.com/humhub-contrib/external_calendar/issues/56 ?

**Comment by kiwiradler** [comment] 2024-01-19 17:56
You can close this issue, it's #56! Thanks for your help. :)

**Comment by marc-farre** [comment] 2024-01-20 08:29
@kiwiradler you are the one who opened this issue, so you can close it (I don't have the right to do it).

**Closed** 2024-01-23 10:47 UTC
